from __future__ import annotations

import json
import re
from typing import Any


def prepare_code_for_execution(
	source_code: str,
	language: str,
	function_name: str = "solve",
	parameter_definitions: list[dict[str, Any]] | None = None,
	return_type: str = "int",
) -> str:
	"""
	Wraps function-based student submissions (e.g. Solution class) with a deterministic I/O driver
	if no main entry point is provided in the source code.
	If student code already has a main entry point or stdin reader, it is left untouched.
	"""
	lang = language.lower().strip()
	fn_name = function_name.strip() or "solve"

	if lang in ("python", "python3", "py"):
		if "from __future__ import annotations" not in source_code:
			source_code = "from __future__ import annotations\n\n" + source_code

		# Check if standard execution block exists
		if "__main__" in source_code or "sys.stdin" in source_code:
			return source_code

		if "class Solution" in source_code or f"def {fn_name}" in source_code:
			param_json = json.dumps(parameter_definitions or [])
			driver = f"""

# --- Autogenerated Execution Harness ---
if __name__ == "__main__":
    import sys, json

    raw_input = sys.stdin.read()
    if raw_input:
        sol = Solution()
        params = json.loads({repr(param_json)})

        # Dynamically parse arguments based on parameter_definitions
        parsed_args = []
        is_single_str = len(params) == 1 and str(params[0].get("type", "")).lower() in ("string", "str")

        if is_single_str:
            parsed_args = [raw_input.rstrip("\\r\\n")]
        elif len(params) == 2 and params[0].get("type") == "int[]" and params[1].get("type") == "int":
            lines = [ln.strip() for ln in raw_input.strip().split("\\n") if ln.strip()]
            if len(lines) == 3:
                nums = [int(x) for x in lines[1].split()]
                target = int(lines[2])
                parsed_args = [nums, target]
            else:
                tokens = raw_input.split()
                if len(tokens) >= 3:
                    n = int(tokens[0])
                    nums = [int(x) for x in tokens[1:n+1]]
                    target = int(tokens[n+1])
                    parsed_args = [nums, target]
        elif len(params) == 1 and params[0].get("type") in ("int[]", "vector<int>", "list[int]"):
            lines = [ln.strip() for ln in raw_input.strip().split("\\n") if ln.strip()]
            if len(lines) == 2:
                nums = [int(x) for x in lines[1].split()]
                parsed_args = [nums]
            elif len(lines) == 1:
                nums = [int(x) for x in lines[0].split()]
                parsed_args = [nums]

        if not parsed_args:
            tokens = raw_input.split()
            for tok in tokens:
                try:
                    parsed_args.append(json.loads(tok))
                except Exception:
                    try:
                        parsed_args.append(int(tok))
                    except ValueError:
                        try:
                            parsed_args.append(float(tok))
                        except ValueError:
                            parsed_args.append(tok)

        # Call method with parsed arguments
        target_name = "{fn_name}"
        if hasattr(sol, target_name):
            fn = getattr(sol, target_name)
        elif hasattr(sol, "solve"):
            fn = getattr(sol, "solve")
        else:
            methods = [m for m in dir(sol) if not m.startswith("_")]
            fn = getattr(sol, methods[0]) if methods else getattr(sol, target_name)

        try:
            if len(parsed_args) == 1 and isinstance(parsed_args[0], list):
                res = fn(parsed_args[0])
            else:
                res = fn(*parsed_args)
            if isinstance(res, bool):
                print(str(res).lower())
            elif isinstance(res, (list, tuple)):
                print(" ".join(str(x) for x in res))
            else:
                print(res)
        except TypeError:
            tokens = raw_input.split()
            res = fn(*tokens)
            print(res)
"""
			return source_code + driver

	elif lang in ("cpp", "c++"):
		if re.search(r"\bint\s+main\s*\(", source_code) or re.search(r"\bvoid\s+main\s*\(", source_code):
			return source_code

		if "class Solution" in source_code:
			driver = """

// --- Autogenerated Execution Harness ---
#include <iostream>
#include <vector>
#include <string>

int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    Solution sol;
    // Driver execution placeholder for function-based problem
    return 0;
}
"""
			return source_code + driver

	elif lang == "java":
		if "public static void main" in source_code:
			return source_code

	elif lang == "c":
		if re.search(r"\bint\s+main\s*\(", source_code) or re.search(r"\bvoid\s+main\s*\(", source_code):
			return source_code

	return source_code
