from __future__ import annotations

import re
from typing import Any


def prepare_code_for_execution(
	source_code: str,
	language: str,
	function_name: str = "solve",
	parameter_definitions: list[dict[str, Any]] | None = None,
	return_type: str = "int",
) -> str:
	"""
	Wraps function-based student submissions (e.g. Solution class) with a deterministic I/O driver
	if no main entry point is provided in the source code.
	If student code already has a main entry point or stdin reader, it is left untouched.
	"""
	lang = language.lower().strip()
	fn_name = function_name.strip() or "solve"

	if lang in ("python", "python3", "py"):
		# Check if standard execution block exists
		if "__main__" in source_code or "sys.stdin" in source_code:
			return source_code

		if "class Solution" in source_code or f"def {fn_name}" in source_code:
			driver = f"""

# --- Autogenerated Execution Harness ---
if __name__ == "__main__":
    import sys, json

    tokens = sys.stdin.read().split()
    if tokens:
        sol = Solution()
        # Parse inputs dynamically based on tokens
        # Try JSON parsing or standard integer/string conversion
        parsed_args = []
        for tok in tokens:
            try:
                parsed_args.append(json.loads(tok))
            except Exception:
                try:
                    parsed_args.append(int(tok))
                except ValueError:
                    try:
                        parsed_args.append(float(tok))
                    except ValueError:
                        parsed_args.append(tok)

        # Call method with parsed arguments
        try:
            fn = getattr(sol, "{fn_name}")
            if len(parsed_args) == 1 and isinstance(parsed_args[0], list):
                res = fn(parsed_args[0])
            else:
                res = fn(*parsed_args)
            if isinstance(res, (list, tuple)):
                print(" ".join(str(x) for x in res))
            elif isinstance(res, bool):
                print(str(res).lower())
            else:
                print(res)
        except TypeError:
            # Fallback passing all tokens as strings
            fn = getattr(sol, "{fn_name}")
            res = fn(*tokens)
            print(res)
"""
			return source_code + driver

	elif lang in ("cpp", "c++"):
		if re.search(r"\bint\s+main\s*\(", source_code) or re.search(r"\bvoid\s+main\s*\(", source_code):
			return source_code

		if "class Solution" in source_code:
			driver = """

// --- Autogenerated Execution Harness ---
#include <iostream>
#include <vector>
#include <string>

int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    Solution sol;
    // Driver execution placeholder for function-based problem
    return 0;
}
"""
			return source_code + driver

	elif lang == "java":
		if "public static void main" in source_code:
			return source_code

	elif lang == "c":
		if re.search(r"\bint\s+main\s*\(", source_code) or re.search(r"\bvoid\s+main\s*\(", source_code):
			return source_code

	return source_code
